name: 🐛 Report a bug
description: Help us improve the Géoplateforme plugin by completing this bug report.
labels: ["bug"]
projects: ["IGNF/4"]
type: "Bug"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A clear and concise description of the problem encountered.
        If possible, include screenshots if they help to explain the issue.
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: A clear and concise description of the behavior you expect to encounter.

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Steps to reproduce the issue
      description: |
        Steps, sample datasets and qgis project file to reproduce the behavior.
        Screencasts or screenshots are more than welcome, you can drag&drop them in the text box.

        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error

        Add pictures if needed.
    validations:
      required: true

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible solution
      description: |
        Optional : only if you have suggestions for how to correct the bug.
        Feel free to create a Pull Request to get a more direct response.

  - type: textarea
    id: about-info
    attributes:
      label: Versions
      description: |
        In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here.
        Do not make a screenshot.
    validations:
      required: true

  - type: checkboxes
    id: qgis-version
    attributes:
      label: Supported QGIS version
      description: |
        Each month, there is a new release of QGIS. According to the release schedule, you should at least be running a supported QGIS version.
        You can check the release schedule https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule
      options:
        - label: I'm running a supported QGIS version according to the official roadmap.

  - type: checkboxes
    id: new-profile
    attributes:
      label: New profile
      description: |
        Did you try with a new QGIS profile? Some issues or crashes might be related to other plugins or specific configuration.
        You must try with a new profile to check if the issue remains.
        Read this link how to create a new profile
        https://docs.qgis.org/3.40/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles
      options:
        - label: I tried with a new QGIS profile

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here.
