blank_issues_enabled: true

contact_links:
  - name: Documentation
    url: https://github.com/Geoplateforme/plugin-qgis-geoplateforme/
    about: Please read carefully the documentation before to submit an issue.
